% Function to create/open custom panel
function openCustomPanel = openCustomPanel(obj)
    if obj.pauseGame == 0 
        obj.pauseGameFcn()
    end
    if isempty(obj.customPanelFig) || ~isvalid(obj.customPanelFig)
        obj.customPanelFig = uifigure('Name', 'Snake Stylist', ...
            'Position', [100 100 450 600], 'Color', [0.12 0.12 0.12]);
        
        % --- HEAD SECTION ---
        uilabel(obj.customPanelFig, 'Text', 'HEAD COLOR (R G B)', ...
            'Position', [25 540 400 35], 'FontColor', [0, 0.9, 0.5], ...
            'FontSize', 24, 'FontWeight', 'bold'); % Increased font to 24
            
        % Edit field for head vector
        obj.colorEditField = uieditfield(obj.customPanelFig, 'text', ...
            'Position', [25 490 400 45], 'FontSize', 25, ... % Taller box, 18pt font
            'Value', num2str(obj.snakeHeadColor), ...
            'BackgroundColor', [0.2 0.2 0.2], 'FontColor', 'w', ...
            'ValueChangedFcn', @(src, event) obj.updateHeadColor(src.Value), ...
            'HorizontalAlignment','center');

        % --- BODY SECTION ---
        uilabel(obj.customPanelFig, 'Text', 'BODY COLOR MATRIX', ...
            'Position', [25 420 400 35], 'FontColor', [1, 0, 1], ...
            'FontSize', 24, 'FontWeight', 'bold'); % Increased font to 24
            
        uilabel(obj.customPanelFig, 'Text', '(One RGB vector per line)', ...
            'Position', [25 395 400 20], 'FontColor', [0.7 0.7 0.7], 'FontSize', 14);

        % Textarea field for matrix body
        obj.bodyTextArea = uitextarea(obj.customPanelFig, ...
            'Position', [25 110 400 280], 'FontSize', 25, ... % Larger text area
            'Value', string(num2str(obj.snakeBodyColor)), ...
            'BackgroundColor', [0.2 0.2 0.2], 'FontColor', 'w', ...
            'ValueChangedFcn', @(src, event) obj.updateBodyColors(src.Value), ...
            'HorizontalAlignment', 'center');

        % apply/close button
        uibutton(obj.customPanelFig, 'Text', 'APPLY & CLOSE', ...
            'Position', [100 30 250 55], 'BackgroundColor', '#4CAF50', ... % Wider, taller button
            'FontSize', 18, 'FontWeight', 'bold', 'FontColor', 'w', ...
            'ButtonPushedFcn', @(~,~) obj.closeCustomPanel());
    else
        figure(obj.customPanelFig);
    end
end